baseURL = "https://kangminsuk.com/"
languageCode = "en-us"
title = "Kang's blog"
theme = "bearcub"
defaultContentLanguage = "en"
enableRobotsTXT = true
dateFormat = "2006-01-02"
email = "kang@jagunbae.com"

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "Kang's blog."
  favicon = "ðŸ“˜"

[languages]
  [languages.en]
    title = "Kang"
    languageName = "English"
    LanguageCode = "en-US"
    contentDir = "content"
    [languages.en.params]
      blogPath = "/blog"
  [languages.ko]
    title = "ê°•ë‹¨"
    languageName = "í•œêµ­ì–´"
    LanguageCode = "ko-KO"
    contentDir = "content.ko"
    [languages.ko.params]
      blogPath = "/ko/blog"